### ISSUE TITLE
No veig la web

### ISSUE THREAD

**Issue by ctrl-alt-d** [WebmentorsEmporda/PaginaWeb#1]
He fet hugo i m'ha generat les pàgines ( a ../docs ) Obro la pàgina principal i està en blanc.

Faig hugo server i la home també està en blanc.

Potser m'haig de descarregar el tema o algo?

**Comment by utrescu** [comment]
Les webs que no són de projectes no poden estar a ' docs': ghpages o màster

Si, has de tenir un tema descarregat. Per exemple

git submodule add https://github.com/budparr/gohugo-theme-ananke.git
themes/ananke;\

El dia 10 febr. 2018 18:32, "dani herrera" <notifications@github.com> va
escriure:

**Comment by ctrl-alt-d** [comment]
sí,

són els submodules, em faltava carregar-los:

```
dh4@GLOW:~/projectes/PaginaWeb$ git submodule init
Submodule 'themes/hugo-now-ui' (https://github.com/cboettig/hugo-now-ui.git) registered for path 'themes/hugo-now-ui'
dh4@GLOW:~/projectes/PaginaWeb$ git submodule update
```
